### ISSUE TITLE
Free Public XMPP Service

### ISSUE THREAD

**Issue by vahid-dan** [ipop-project/ipop-project.github.io#27]
Current sample config file is useless for end-users unless they have access to an XMPP server. I think we should have a wiki page on how to create an XMPP user on a free public service.

**Comment by vahid-dan** [comment]
We also should have at least one node up 24/7 for end-users to ping and test if their setup network is working fine.

**Comment by renatof** [comment]
I think pointing to a public XMPP service is a good idea; are there any
good options to replace dukgo?

As for deploying a test node, that would be very challenging, because we'd
need to worry about IP address collision, and either distributing a
password, or becoming friends with each user that wants to try it out. I'd
rather give instructions for users on how to deploy two nodes and test it
themselves.

--rf

**Comment by vahid-dan** [comment]
DuckDuckGo team has advertised a link to a page introducing several free XMPP servers:
https://www.cryptoparty.in/connect/contact/jabber

Among them, I have tested xmpp.is which is apparently working fine:
https://xmpp.is/

I just connected my Ubuntu laptop and RPi and they can ping each other. We should test it thoroughly, though.
