### ISSUE TITLE
 Is there any more information about the changes in version 17.08 of IPOP?

### ISSUE THREAD

**Issue by goldsoft8888** [ipop-project/ipop-project.github.io#49]
1.  Can IPOP 17.08 prevent DHCP from spreading in IPOP VPN networks?

2. Bi-directional NAT traversal attempts
Do you support the implementation of symmetric NAT traversal with STUN server?

3. does it support a list of STUN servers? For example, multiple STUN servers

**Comment by goldsoft8888** [comment]
If you build a 32 bit system, different CPU, and IPOP-VPN FOR OPENWRT, how to achieve?

**Comment by vahid-dan** [comment]
> If you build a 32 bit system, different CPU, and IPOP-VPN FOR OPENWRT, how to achieve?

Our Raspberry Pi 3 and Raspberry Pi Zero editions are 32 bit, not 64 bit.
Basically, if you can build WebRTC libraries for your machine, you most probably should be able to build IPOP for that machine, as well.
About OpenWRT, we are trying to build IPOP for OpenWRT on ARMv6 and I hope we can do it in a few weeks. Technically, it should be very similar to our Raspberry Pi 3 and Raspberry Pi Zero since the architecture is similar.

Bests,
Vahid

**Comment by goldsoft8888** [comment]
Thanks

**Comment by kcratie** [comment]
@goldsoft8888  
Current only a single STUN and a single TURN server is used. 
NAT traversal does not work behind symmetric NAT, it requires relay using TURN.
IPOP does not attempt to block DHCP on the overlay.

**Comment by goldsoft8888** [comment]
@kcratie 
BroadcastForwarder.Enabled
Does this parameter prevent the spread of DHCP?

**Comment by gurussia** [comment]
goldstoff you install and you run ipop.

Please help. we want implement ipop in ejabberd but on ubuntu latest version it comment error:

https://github.com/ipop-project/ipop-project.github.io/issues/62

im wiriting you becouse maybe developers will not comment from 1 month, so when you read this message please help, how to are obsolete and it comment errors in python2 or python3.

**Comment by vahid-dan** [comment]
Closed due to inactivity. Feel free to re-open it if needed.
